workspaces:
projects:
langs:
    - id: def_nodejs
      name: Node.js
      is_default: true
    - id: "1766633490617"
      name: Html
      is_default: false
    - id: def_java
      name: Java
      is_default: true
    - id: def_python
      name: Python
      is_default: true
    - id: def_golang
      name: Golang
      is_default: true
    - id: def_rust
      name: Rust
      is_default: true
app_types:
    - id: def_web
      name: web
      is_default: true
    - id: def_wap
      name: wap
      is_default: true
    - id: def_app
      name: 独立应用程序
      is_default: true
    - id: def_service
      name: web服务应用
      is_default: true
    - id: def_api
      name: api
      is_default: true
node_providers:
    - id: def_aws_cloud
      name: AWS
      is_default: true
    - id: def_tencent_count
      name: Tencent (腾讯云)
      is_default: true
    - id: def_azure_cloud
      name: Azure
      is_default: true
    - id: def_aliyun
      name: Aliyun (阿里云)
      is_default: true
    - id: def_huawei_cloud
      name: Huawei (华为云)
      is_default: true
    - id: def_google_cloud
      name: Google Cloud
      is_default: true
    - id: def_local_service
      name: Local (自建/其他)
      is_default: true
    - id: def_baidu_cloud
      name: Huawei (百度云)
      is_default: true
